astar_planner:
  ros__parameters:
    planner:
      type: "HybridAStar"
      debug_visualization: false
      theta_resolution: 72.0 # number of discrete theta values
      xy_tolerance: 0.25 # meters
      theta_tolerance: 0.45 # radians
      timeout: 40.0 # seconds
      min_velocity: 0.3 # meters per second
      use_dynamic: false
      allow_reverse: false
      wheelbase: 2.0 # meters
      max_velocity: 0.7 # meters per second
      min_linear_acc: 0.1 # meters per second squared
      steer_resolution: 10.0 # degrees
      max_steer: 40.0 # degrees

    map:
      width: 20.0
      height: 20.0
      resolution: 0.1
