astar_planner:
  ros__parameters:
    planner:
      type: "HybridAStar"
      debug_visualization: true
      theta_resolution: 62.8
      xy_tolerance: 0.1
      theta_tolerance: 0.1
      timeout: 120.0
      min_velocity: 0.3
      use_dynamic: false
      allow_reverse: false
      wheelbase: 2.0
      max_velocity: 0.7
      min_linear_acc: 0.1
      steer_resolution: 5.625
      max_steer: 33.75

    map:
      width: 20.0
      height: 20.0
      resolution: 0.1
